# Generated by Django 5.2 on 2025-09-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_image_product_thumbnail_remove_product_name_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
